  sudo: true
  language: python
  cache: pip
  python:
    - "3.5"
    - "3.6"
  before_install:
  - chmod +x install_requirements.sh
  
  addons:
    apt_packages:
      - swig
      - libpulse-dev

  install:
     - ./install_requirements.sh
  script:
    - pytest test/

  