  sudo: true
  language: python
  python:
    - "3.5"
    - "3.6"
  before_install:
  - chmod +x install_requirements.sh
  
  addons:
  apt_packages:
    - swig
  
  install:
     - ./install_requirements.sh
  script:
    - pytest test/

  